[package]
name = "alfad-compile"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["derive"] }
alfad = {path= "../core"}
postcard = { version = "1.0.8", features = ["alloc"] }
serde = { version = "1.0.201", features = ["derive"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
